### ISSUE TITLE
Problem with roc.analysis output

### ISSUE THREAD

**Issue by lozanoje** [lozalojo/mem#6]
Coming from:

https://github.com/lozalojo/mem/issues/5

**Comment by lozalojo** [comment]
> When I use the example sentences of "roc.analysis", I find that if I set different parameter ranges (1-5 or 2-4), I get different sensitivity, specificity, etc. This phenomenon also occurs on "memapp" when I adjust the parameters from 1-5 to 2-4. It seems to be related to "i.detection.values".

Yes, memgoodness use a range of values when detecting epidemics with memtiming, that range of "possible" values are set in the i.detection.param or the range set at memapp. Different ranges produce different results.

More info on the process:

https://github.com/lozalojo/memapp/blob/assets/technicalmanual.pdf

> For the "mem" program, if I want to use the "fixed criterium method" to optimize the model and set the parameters to range from 2-4, which parameter do I need to set ("i.detection.value" or "i.param") , or they need to set the same range? 

memapp uses the same range (set in the program options) for i.param.values and i.detection.values, so:

```r
temp1 <- roc.analysis(i.data=flucyl, i.param.values = seq(2, 4, 0.1), i.detection.values=seq(2, 4, 0.1))
```

> When I set "i.detection.values" it iterates from 1 to 5 regardless of the parameter range. Using the same criteria to select optimal parameters, Youden's index, results will vary due to differences in specificity and sensitivity. Setting a different "i.param.values" parameter range does not affect the result. The results for specificity and sensitivity were consistent. When setting different "i.param.values" parameter ranges does not affect the result. The results of specificity and sensitivity were consistent. My problem may be not understanding the difference and connection between "i.param.values" and "i.detection.values".

i.param.values = values to be tested, evaluate and chose the best one depending on the criteria you prefer
i.detection.values = to calculate goodness you need "observed epidemics" and "expected/real epidemics", to have True positive, True negative, False positive and False negative and be able to calculate indicators. The problem is to know which is the "real epidemic", since it is probable that two different observers detect different epidemics. So the real thing is different to evaluate. We use memtiming (see the function and the use), and memtiming relies on a paramenter i.param, this parameter can be interpreted as different observers detect different epidemic periods in the same season. Since we do not know which one is the right one, we simulate different observers using different parameters of i.param, and summarise the results. So i.detection.param is a range of values used to detect the real epidemics, simulating a pool of observers/experts saying where do they think the epidemic is located. Then we pool the results of TP, TN, FP, FN of different detection parameters and summarize the results.

More info on the process:

https://github.com/lozalojo/memapp/blob/assets/technicalmanual.pdf

**Comment by 13367356107** [comment]
Thank you for your answer.
